name: Deploy

on:
  push:
    branches:
      - github_actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Bun environment
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install
        working-directory: ./

      # Step 4: Install Cargo and wasm-pack
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        working-directory: ./

      # Step 5: Build the website
      - name: Build Website
        run: bun run build
        working-directory: ./

      # Step 6: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-1'

      # Step 7: Deploy to S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} \
            --delete \
            --follow-symlinks \
            --size-only \
            --exclude "*" \
            --include "*.html" \
            --include "*.js" \
            --include "*.css" \
            --include "*.wasm" \
            --include "*.svg" \
            --include "*.png" \
            --include "*.jpg" \
            --include "*.json" \
            --cache-control "max-age=86400"
